
%% ------------------------------------------------------------------------
%%% AMPC Project Presented by

%%% Ibrahim Bashir Attawil 

%%% 7/2023

%% ------------------------------------------------------------------------
%% General Model Parameters
Ts = 0.1;  % Simulation sample time                (s)
scenarioTime=500;  % scenario time (s) to make a round set the time 480s
addpath('simulink files');

%% controller object
load("AMPC.mat");
%% controller structure 
load('pfcsubsystem_data_2.mat');
%% open simulink model
open_system('AMPC_Lane_Following_Project')
%% Create scenario and road specifications
% curved road scenario. This function was generated by the Driving
% Scenario Designer.
[scenario,egoVehicle] = cDrivingScenario();


%% Generate data for Simulink simulation
egoID = egoVehicle.ActorID;
[driverPath,x0_ego,y0_ego,v0_ego,yaw0_ego,simStopTime] = ...
    createDriverPath(scenario,egoID,6);

%% Bus Creation
% Create buses for lane sensor and lane sensor boundaries
createLaneSensorBuses

%% Run 

simout=sim('AMPC_Lane_Following_Project'); % Simulate to end of scenario
%% plot
x=simout.x_simout.signals.values;
y=simout.y_simout.signals.values;
scenario.Actors.Position =[x(end),y(end),0];
coPlotLFResults(scenario,x,y)

